import React from 'react'
import { Container } from 'react-bootstrap'

const page = () => {
    return (
        <>
            <Container className='pt-3'>
                <h1 style={{ fontSize: "36px", fontWeight: "600", color: "black" }}> Terms And Conditions</h1>
                <p className='term-text'>
                    IMPORTANT: THESE TERMS OF USE CONTAIN A MANDATORY ARBITRATION PROVISION THAT, AS FURTHER SET FORTH IN SECTION 20 BELOW, REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES. THIS MEANS THAT YOU AND TMC Global ARE EACH GIVING UP THE RIGHT TO SUE EACH OTHER IN COURT OR IN CLASS ACTIONS OF ANY KIND. IN ARBITRATION, THERE IS NO JUDGE OR JURY AND THERE IS LESS DISCOVERY AND APPELLATE REVIEW THAN IN COURT

                </p>
                <p className='term-text'>
                    1. Introduction
                </p>
                <p className='term-text'>

                    Welcome to the family of websites provided by TMC Global. These Terms of Use govern your access to and use of all TMC Global Sites among other things. By using the TMC Global Sites, you affirm that you are of legal age to enter into these Terms of Use, or, if you are not, that you have obtained parental or guardian consent to enter into these Terms of Use and your parent or guardian consents to these Terms of Use on your behalf. If you violate or do not agree to these Terms of Use, then your access to and use of the TMC Global Sites is unauthorized. Those terms and conditions can be found where the relevant service is offered on the TMC Global Sites or otherwise and are incorporated into these Terms of Use by reference

                </p>
                <p className='term-text my-5'>
                    DEFINED TERMS
                </p>

                <p className='term-text'>
                    In these Terms of Use:
                </p>
                <p className='term-text'>
                    When we say “TMC Global,” we mean tmcglobal.com USA, LLC and TMC Global Inc., and any subsidiaries of TMC Global Stores, Inc. (including any subsidiaries that TMC Global Inc. may form or acquire in the future), and their affiliates, directors, officers, employees and agents. We also refer to TMC Global as “we,” “us” and “our.” But when we say “TMC Global Entities,” we mean TMC Global; its suppliers, vendors, contractors, and licensors.
                </p>
                <p className='term-text'>
                    When we say “TMC Global Sites,” we mean www.tmcglobal.com,<br />
                    When we say “you” or “your” we mean any user (like you!) of any TMC Global Site <br />and any person who has notice of these Terms of Use.
                    When we say “Terms of Use,” we mean these Terms of Use and all other terms and policies posted by TMC Global on the TMC Global Sites (and any updates by TMC Global to these Terms of Use and those terms and policies)
                </p>
                <p className='term-text'>
                    A few other key terms used in these Terms of Use:<br />
                    When we say “Content,” we mean merchandise information, product descriptions, reviews, comments, messages, reviews, communications, feedback, submissions, suggestions,<br /> questions, and other information, data, content, and materials (including page headers, images, text, illustrations, formats, logos, hashtags, designs, icons, photographs, software programs, music clips or downloads, video clips, and written and other materials.)<br />
                    When we say “Ideas,” we mean ideas, concepts, feedback, and know-how that you make available in connection with the TMC Global Sites.
                    When we say “make available,” we mean post, transit, publish, upload, distribute, transmit, display, provide, or otherwise submit or make available (including through any part of the TMC Global Sites administrated by third-party social media platforms (e.g., Facebook or Instagram) that allow interaction with the TMC Global Sites through the tools offered by such social media platforms).
                </p>
                <p className='term-text'>
                    When we say “Materials,” we mean Content that TMC Global Entities make available on or through the TMC Global Sites, including In Store Now information.<br />
                    WARRANTY DISCLAIMERS AND LIABILITY LIMITATIONS: While there are important points throughout these Terms of Use, please note the warranty disclaimers and limitations on TMC Global’s liability explained in Sections 17 and 18, respectively
                </p>
                <p className='term-text'>
                    UPDATES: We may update these Terms of Use from time to time by notifying you of such changes by any reasonable means, including by posting a revised Terms of Use through the TMC Global Sites. Any such changes will not apply to any dispute between you and us arising prior to the date on which we posted the revised Terms of Use incorporating such changes or otherwise notified you of such changes. You agree that it your responsibility to regularly check TMCGlobal.com for any updated Terms of Use. In addition, by continuing to use or access any of the TMC Global Sites or otherwise engaging with TMC Global after we post any changes, you accept the updated Terms of Use. The “Last Updated” legend above indicates when these Terms of Use were last changed.
                </p>

                <p className='term-text'>

                    2. Your Use of the TMC Global Sites<br />
                    You certify that the Content you provide on or through the TMC Global Sites is accurate and that the information you provide on or through the TMC Global Sites is complete. You are solely responsible for maintaining the confidentiality and security of your account including username, password, and PIN. TMC Global is not responsible for any losses arising out of the unauthorized use of your account. You agree that TMC Global does not have any responsibility if you lose or share access to your device. Any agreement between you and the issuer of your credit card, debit card, or other form of payment will continue to govern your use of such payment method on the TMC Global Sites. You agree that TMC Global is not a party to any such agreement, nor is TMC Global responsible for the content, accuracy, or unavailability of any method used for payment. Your account may be restricted or terminated for any reason, at our sole discretion. Except as otherwise provided by law, at any time without notice to you, we may (1) change, restrict access to, suspend, or discontinue the TMC Global Sites or any portion of the TMC Global Sites, and (2) charge, modify, or waive any fees required to use any services, functionality or other content available through the TMC Global Sites or any portion of the TMC Global Sites.
                </p>

                <p className='term-text'>
                    In connection with the TMC Global Sites, you will not:<br />
                    Make available any Content through or in connection with the TMC Global Sites that is or may be in violation of the content guidelines set forth in Section 3.C (Prohibited Content) below.<br />
                    Make available through or in connection with the TMC Global Sites any virus, worm, Trojan horse, Easter egg, time bomb, spyware, or other computer code, file or program that is or is potentially harmful or invasive or intended to damage or hijack the operation of, or to monitor the use of, any hardware, software, or equipment.
                    Use the TMC Global Sites for any commercial purpose, or for any purpose that is fraudulent or otherwise tortious or unlawful.<br />
                    Harvest or collect information about users of the TMC Global Sites.
                    Interfere with or disrupt the operation of the TMC Global Sites or the systems, servers, or networks used to make the TMC Global Sites available, including by hacking or defacing any portion of the TMC Global Sites; or violate any requirement, procedure or policy of such servers or networks.
                    Restrict or inhibit any other person from using the TMC Global Sites.<br />
                    Reproduce, modify, adapt, translate, create derivative works of, sell, rent, lease, loan, timeshare, distribute, or otherwise exploit any portion of (or any use of) the TMC Global Sites except as expressly authorized in these Terms of Use, without TMC Global’s express prior written consent.
                    Reverse engineer, decompile, or disassemble any portion of the TMC Global Sites, except where such restriction is expressly prohibited by applicable law.<br />
                    Remove any copyright, trademark, or other proprietary rights notice from the TMC Global Sites.<br />
                    Frame or mirror any portion of the TMC Global Sites, or otherwise incorporate any portion of the TMC Global Sites into any product or service, unless you obtain TMC Global’s express prior written consent to do so.<br />
                    Systematically download and store any Materials.<br />
                    Use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, “scrape,” “data mine” or otherwise gather any Materials, or reproduce or circumvent the navigational structure or presentation of the TMC Global Sites, without TMC Global’s express prior written consent.<br />
                    Cause injury to any person or entity.<br />
                    Violate any law, rule, or regulation, or these Terms of Use.<br />
                    You will not use the TMC Global Sites or TMC Global’s name, logo, or brand to (1) send any unsolicited or unauthorized Content, including advertising, promotional materials, email, junk mail, spam, or other form of solicitation; or (2) use any meta tags or other hidden text or metadata utilizing a TMC Global trademark, logo, URL, or product name without TMC Global’s written consent;<br />
                    You will not attempt to do anything, or permit, encourage, assist, or allow any third party to do anything, prohibited in this Section, or attempt, permit, encourage, assist, or allow any other violation of these Terms of Use.<br />
                    3. Content and Ideas<br />
                    A. Submitting Content and Ideas<br />
                    TMC Global provides functionality that enables users to make available Content and Ideas in connection with the TMC Global Sites. Any text in Content should be written in English. You acknowledge and agree that you are responsible for all Content and Ideas you make available in connection with any TMC Global Site. You represent and warrant that (1) you have the authority to grant the rights in such Content and Ideas as set forth in these Terms of Use, including in Section 3(B) below; and (2) such Content and Ideas, and the use of such Content and Ideas, will not violate any term of these Terms of Use. This means you will be responsible for the legality, the accuracy, the appropriateness, the originality, and your rights in any such Content and Ideas.
                </p>

                <p className='term-text'>
                    B. TMC Global’s Rights to Use Content and Ideas<br />
                    You grant to TMC Global a royalty-free, perpetual, irrevocable, worldwide, unlimited, nonexclusive license to use, reproduce, create derivative works from, modify, publish, edit, translate, distribute, perform and display (publicly or otherwise) any Content that you make available,<br /> in any media or medium, and in any form, format, or forum now known or hereafter developed. You further agree that TMC Global  is free to use any Ideas for any purpose. TMC Global may sublicense its rights in Content and Ideas through multiple tiers of sublicenses. TMC Global is, and will be, under no obligation (1) to maintain any Content or Idea in confidence; (2) to pay any compensation for any Content or Idea; or (3) to respond to any Content or Idea. You grant to TMC Global the right to use any name associated with any Content or Idea that you make available to TMC Global , although TMC Global has no obligation to exercise such right, or to otherwise provide any attribution for any Content or Idea
                </p>

                <p className='term-text'>
                    C. Prohibited Content<br />
                    You agree that you will not make available Content in connection with the TMC Global Sites that:
                </p>

                <p className='term-text'>
                    is false, fraudulent, inaccurate, or misleading;<br />
                    contains your full name(s), or any other confidential personally identifiable information of yourself or others;<br />
                    violates any local, state, federal, or international laws or is otherwise tortious;<br />
                    is protected by or would infringe on the rights of others (including TMC Global), including any patent, copyright, trademark, trade secret, right of publicity or privacy, or any other proprietary right, without the express prior written consent of the applicable owner;
                    is obscene, indecent, pornographic, or otherwise objectionable;<br />
                    is derogatory, defamatory, threatening, harassing, abusive, slanderous, hateful, or embarrassing to any other person or entity as determined by TMC Global in its sole discretion;
                    victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age or disability;
                    is violent or threatening, or promotes violence against, or actions that are threatening to, any individual or group;<br />
                    contains advertisements, solicitations, or spam links to other web sites or individuals, without prior written permission from TMC Global;
                    contains or relates to chain letters or pyramid schemes;<br />
                    impersonates another business, person, or entity, including TMC Global, its related entities, employees, and agents;<br />
                    violates any policy posted on the TMC Global Sites; or
                    is intended to cause harm, damage, disable, or otherwise interfere with the TMC Global Sites or our partners.<br />
                    4. Monitoring by TMC Global<br />
                    TMC Global will have the right (but not the obligation), in our sole discretion, to monitor, evaluate, and analyze Content, and any use of and access to the TMC Global Sites, including to determine compliance with these Terms of Use and any other operating rules that may be established by TMC Global from time to time. TMC Global will also have the right (but not the obligation), in our sole discretion, to edit, move, delete, or refuse to make available any Content made available through, the TMC Global Sites, for any reason, including violation of these Terms of Use, whether for legal or other reasons. Despite this right of ours, you are solely responsible for any Content you make available, and you agree to indemnify TMC Global for all claims resulting from any Content you make available.<br />

                    5. Materials Available on the TMC Global Sites<br />
                    TMC Global and its suppliers and licensors may make available various Materials. The Materials are for educational and informational purposes only, and errors may appear from time to time. Before you act in reliance on any Materials, you should confirm any facts that are important to your decision. The TMC Global Entities make no warranty as to the reliability, accuracy, timeliness, usefulness, or completeness of any Materials. If you find an error or notice something that does not look quite right on the TMC Global Sites, we would appreciate it if you let us know by contacting us at http://www.tmcglobal.com/help (Your feedback is a big part of what helps TMC Global to get better at helping you!)

                    NO MATERIALS RELATED TO HEALTH, WELLNESS, PRESCRIPTIONS, OR PHARMACEUTICALS ARE INTENDED TO SUBSTITUTE FOR THE DIAGNOSIS,<br /> TREATMENT AND ADVICE OF A MEDICAL PROFESSIONAL, AND SUCH MATERIALS DO NOT COVER ALL POSSIBLE USES, PRECAUTIONS, SIDE EFFECTS, AND INTERACTIONS, AND SHOULD NOT BE CONSTRUED TO INDICATE THAT ANY DRUG IS SAFE OR EFFECTIVE FOR YOU. CONSULT THE PRODUCT INFORMATION (INCLUDING PACKAGE INSERTS) REGARDING DOSAGE, PRECAUTIONS, WARNINGS, AND INTERACTIONS, AND YOUR MEDICAL PROFESSIONAL, FOR GUIDANCE BEFORE USING ANY PRESCRIPTION OR OVER-THE-COUNTER DRUG.

                    THE TMC Global ENTITIES ASSUME NO RESPONSIBILITY FOR ANY CONSEQUENCE RELATING DIRECTLY OR INDIRECTLY TO ANY ACTION OR INACTION YOU TAKE BASED ON THE MATERIALS.
                </p>

                <p className='term-text'>
                    6. Merchandise<br />
                    The Sites may make available listings, descriptions, and images of goods and services (collectively, “Products”). <br />Such Products may be made available by us or by third parties. We make no representations as to the completeness, accuracy, reliability, validity, or timeliness of such listings, descriptions, or images (including any features, specifications, and prices contained on the Sites). Such information and the availability of any Product are subject to change at any time without notice.

                    We have made efforts to accurately display the attributes of Products, including the applicable colors. However, as the actual colors you see will depend on your monitor, we cannot guarantee that your monitor's display of any color will accurately reflect actual product color or finish. In addition, certain weights, measures, and similar descriptions are approximate and are for convenience only.

                    We sell Products for children’s use; however, these Products are intended for sale to adults.<br />

                    TMC Global has no liability to you for content on the TMC Global Sites that you find to be offensive,<br /> indecent, or objectionable. Certain videos, movies, TV programs, video games, computer games, and other Products are labeled with age restrictions or are intended for individuals of certain ages or “mature audiences” only. By ordering an age restricted item, you certify that you satisfy the age restrictions.

                    TMC Global is not responsible for, and cannot guarantee the performance of, goods and services provided by third parties, including any TMC Global Entity, Marketplace Retailer (as defined below in Section 16.A), our advertisers, or other third parties to whose sites we link. While our goal is to provide accurate information, product packaging and material may contain more and/or different information than that provided on TMC Global Sites, including the product description, country of origin, nutrition, ingredient, allergen, and other information. Always read labels, warnings, directions, and other information provided with the product before using or consuming the product. For additional information about a product, please contact the manufacturer. Information and statements regarding dietary supplements have not been evaluated by the Food and Drug Administration and are not intended to diagnose, treat, cure, or prevent any disease or health condition. If you find a product is not as described, your sole remedy is to return it in unused condition (excluding products that are not eligible for return), in accordance with TMC Global’s return policy. It is your responsibility to ascertain and obey all applicable local, state, federal, and foreign laws (including minimum age requirements) regarding the purchase, possession, and use of any Product
                </p>

                <p className='term-text'>
                    7. Third Party Sites<br />
                    References on TMC Global Sites to any names, marks, products, or services of third parties, or links to third-party sites or information, are not an endorsement, sponsorship, or recommendation of the third party or its information, products, or services. TMC Global is not responsible for the content of any third-party linked site or any link contained in a linked site, including any third-party social media with which the TMC Global Sites operate or otherwise interact, nor is TMC Global responsible for the acts or omissions of any operator of any such site or platform. Your use of any such third-party site or platform is at your own risk, and will be governed by such third party's terms and policies (including its privacy policy).
                </p>
                <p className='term-text'>
                    8. Placing an Order<br />
                    A. Order Acceptance and Billing<br />
                    You represent and warrant that you have the right to use any credit card or other means of payment that you provide to us. By providing payment card information to us, you authorize us to store and use the card as a payment method for purchases made through your tmcglobal.com account, including on TMC Global affiliated sites and properties which you access via your tmcglobal.com account credentials. TMC Global participates in account update services offered by some banks. If your bank participates in account updater services, these services will automatically update your card number or expiration date in our system when it changes. If you do not want to have your cards automatically updated, you can opt out of these services by contacting your issuing bank. All billing information you provide to us must be truthful and accurate. Providing any untruthful or inaccurate information is a breach of these Terms of Use and may result in cancellation of your order. Prior to accepting an order we may also request additional information from you. Verification of information may be required prior to the acknowledgment or completion of any purchase. We reserve the right to refuse or cancel an order for any reason including limitations on quantities available for purchase, inaccuracies, or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. If your order is canceled after your credit card (or other payment account) has been charged, we will issue a credit to your credit card (or other applicable payment account) in the amount of the charge. We will attempt to contact you if all or any portion of your order is canceled or if additional information is required to accept your order. TMC Global may request a pre-authorization for some orders placed online with a credit or debit card. This pre-authorization will not be billed to you; however, your card issuer may hold this amount for a short period. Your card issuer determines the length of time the pre-authorization is held. We do this to ensure that the card details are still valid and that you have sufficient funds to complete the transaction.
                </p>

                <p className='term-text'>
                    By confirming your purchase at the end of the checkout process, you agree to accept and pay for the Products, as well as all shipping and handling charges and applicable taxes and fees. You will not be charged for most orders until the order has shipped. Some exceptions (when you will be charged at the time your order is placed) are: (i) orders or preorders paid for with a Gift Card, eGift Card, or PayPal account; and (ii) orders paid using the in-store “Cash” payment method
                </p>
                <p className='term-text'>
                    TMC Global reserves the right, including without prior notice, to limit the quantity of items purchased per person, per household, or per order for any reason. We will attempt to notify you should such limits be applied. TMC Global also reserves the right, at our sole discretion, to prohibit sales to dealers or resellers. For purposes of these Terms of Use, “reselling” will be defined as purchasing or intending to purchase any Product(s) from TMC Global for the purpose of engaging in a commercial sale of the same Product(s) to a third party.
                </p>
                <p className='term-text'>
                    In addition to any other remedies available to it, TMC Global may in its sole discretion restrict or terminate your account, or cancel or refuse orders for violations of, or abuse of the TMC Global returns policy
                </p>

                <p className='term-text'>

                    10. Export Policy
                    You acknowledge that (a) goods licensed or sold on the TMC Global Sites, and (b) any software or technology purchased, downloaded, or used from the TMC Global Sites, are subject to the customs and export control laws and regulations of the United States of America and may also be subject to the customs and export laws and regulations of the country in which the products are manufactured and/or received, and you agree to comply with all applicable laws. You agree, represent, and warrant that no Materials will be accessed from, downloaded in, released in, carried to, transferred to, transshipped through, exported to, or re-exported (collectively “transferred”) to any territory (or national resident thereof), person, entity, or organization to which such Materials could not be transferred directly from the United States or by a U.S. person without a license, including without limitation to any person on the U.S. Treasury Department’s List of Specially Designated Nationals or the U.S. Department of Commerce’s Denied Persons List or Entity List.<br />

                    11. Intellectual Property<br />
                    The TMC Global Sites and all Materials, and all copyrights, trademarks, trade dress,<br /> and other intellectual property rights there (collectively, the “IP”) are owned or controlled by or licensed to TMC Global, and are protected by U.S. and international trademark, copyright, and other intellectual property laws. Materials are licensed (not sold) to end users. Subject to your compliance with these Terms of Use, and solely for so long as you are permitted by TMC Global to use the TMC Global Sites, you may access, view, download, and print the Materials for your personal, non-commercial use only; provided, however, that you (1) retain all copyright, trademark, or other proprietary designations contained on all Materials; (2) do not modify or alter the Materials in any way; and (3) do not provide or make available the Materials to any third party in a commercial manner.

                    No license, right, title, or interest in the TMC Global Sites or any Materials is transferred to you as a result of your use of the TMC Global Sites or your accessing, viewing, downloading, or printing of the Materials. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell, or participate in any sale of or exploit in any way, in whole or in part, any of the Materials or the TMC Global Sites. The TMC Global Sites and Materials may be used only as a personal shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the TMC Global Sites and the Materials is strictly prohibited. The compilation (meaning the collection, arrangement, and assembly) of the TMC Global Sites and Materials is the exclusive property of TMC Global and is also protected by U.S. and international copyright laws.<br />

                    TMC Global, WAL-MART, the TMC Global.COM names and logos, and all other graphics, logos, page headers, button icons, scripts, and service names included in or made available through any of the TMC Global Sites are trademarks or trade dress of TMC Global in the U.S. and other countries. All other marks are the property of their respective companies.

                    12. Procedure for Making a Claim of Copyright Infringement<br />
                    We respect the intellectual property of others. If you believe that your work has been copied and is accessible on the TMC Global Sites in a way that constitutes copyright infringement, please see our DMCA Procedure for instructions on how to contact us to report possible copyright infringement
                </p>

                <p className='term-text'>
                    13. Privacy<br />
                    You acknowledge that any personal information that you provide through the TMC Global Sites will be used by TMC Global in accordance with TMC Global’s Privacy Policy, which may be updated by TMC Global from time to time. If you purchase an item on tmcglobal.com sold by a Marketplace Retailer or a TMC Global supplier, TMC Global may share certain information with that Marketplace Retailer or supplier to permit the Marketplace Retailer or supplier, as applicable, to fulfill and ship your order, process returns, and provide customer service.

                    You authorize your wireless operator (AT&T, Sprint, T-Mobile, US Cellular, Verizon, or any other branded wireless operator) to disclose to TMC Global and its third-party service providers your mobile number, name, address, email, network status, customer type, customer role, billing type, mobile device identifiers (IMSI and IMEI) and other subscriber status and device details, if available, solely to verify your identity and prevent fraud for the duration of the business relationship. See the TMC Global Privacy Policy for how TMC Global treats your data.

                    14. Third-Party Software & Licensing Notices<br />
                    The TMC Global Sites may include certain third-party technologies and open source materials (collectively, “Third-Party Technology”). Your use of such Third-Party Technology is subject to these Terms of Use, as well as well the applicable terms and conditions of such third parties,.

                    15. Promotions<br />
                    Any sweepstakes, contests, raffles, surveys, games, or similar promotions (collectively, “Promotions”) made available through the TMC Global Sites may be governed by rules that are separate from or supplement these Terms of Use. If you participate in any Promotions, please review the applicable rules as well as our Privacy Policy. If the rules for a Promotion conflict with these Terms of Use, the Promotion rules will govern.

                    TRIPLE10 promo code: Valid only for your first 3 orders with TMC Global pickup & delivery services. Minimum order of N50. Does not apply to alcohol purchases. Customer responsible for all applicable taxes. Offer subject to change or expire without notice.

                    TRIPLE20 promo code: Select customers only. Valid only for your next 3 orders with TMC Global pickup & delivery services. Minimum order of N50. Does not apply to alcohol purchases. Customer responsible for all applicable taxes. Offer subject to change or expire without notice.

                    REDBULL1 promo code: Valid only for your first 3 orders with TMC Global pickup & delivery services. Minimum order of N50. Does not apply to alcohol purchases. Customer responsible for all applicable taxes. Offer subject to change or expire without notice.

                    10OFF3 promo code: Valid only for your first 3 orders with TMC Global pickup & delivery services. Minimum order of N50. Does not apply to photo, personalized items, pharmacy, gift cards, alcohol, or items sold by Marketplace sellers. Customer responsible for all applicable taxes. Cannot be combined with other special offers. Offer subject to change or expire without notice.<br />

                    HOLIDAY10: Valid only for your first 3 orders with TMC Global pickup & delivery services. Minimum order of N50. Discount will be applied to your total basket value, excluding photo, personalized items, pharmacy, gift cards, alcohol or items sold by Marketplace sellers. This offer can’t be used for photo, personalized items, pharmacy, gift cards, alcohol or items sold by Marketplace sellers. Customer responsible for all applicable taxes. This offer may not be combined with other special offers.<br />

                    TODAY10 promocode: Valid only for your first 3 orders with TMC Global pickup & delivery services. Minimum order of $50. Discount will be applied to your total basket value, excluding photo, personalized items, pharmacy, gift cards, alcohol or items sold by Marketplace sellers. This offer can’t be used for photo, personalized items, pharmacy, gift cards, alcohol or items sold by Marketplace sellers. Customer responsible for all applicable taxes. This offer may not be combined with other special offers. Offer subject to change or expire without notice.<br />
                </p>

                <p className='term-text'>
                    16. Terms Applicable to Special TMC Global Services<br />
                    A. TMC Global Marketplace<br />
                    TMC Global operates an online marketplace program on the TMC Global Sites which enables Marketplace Retailers to sell their products alongside TMC Global products and, once an order is placed, to ship such Marketplace Retailers’ products directly to the customer (the “TMC Global Marketplace”). Any use of the TMC Global Marketplace is subject to the following additional terms:

                    When we say “Marketplace Retailer,” we mean any entity or retailer that sells goods or services in the TMC Global Marketplace through the TMC Global Sites, uses any order processing, fulfillment, shipping, or other services related to the TMC Global Marketplace provided by or for TMC Global, or uses any platform, portal, web service, application, interface, or other tool provided by or for TMC Global in connection with the TMC Global Marketplace.<br />
                    By purchasing a product from any of our Marketplace Retailers, you acknowledge that all TMC Global Marketplace orders will be fulfilled by the third party Marketplace Retailer and not TMC Global. The Marketplace Retailer (and not TMC Global) will be responsible for all processing, shipping, returns, and customer service related to your TMC Global Marketplace order. Products purchased from a Marketplace Retailer can only be returned to that Marketplace Retailer in accordance with its return policy. Each Marketplace Retailer’s shipping information, return policy, customer service information, and Marketplace Privacy Policy can be found on that Marketplace Retailer’s Seller Information page. For other terms that apply to TMC Global Marketplace, including important notices and disclosures, see About Marketplace.<br />
                    To the fullest extent provided by applicable law, TMC Global has no responsibility or liability for any Marketplace Retailer, their products, or representations.

                    You represent and warrant that (1) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (2) you are not listed on any U.S. Government list of prohibited or restricted parties.
                    Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms of Use and, upon your acceptance of the terms and conditions of these Terms of Use, will have the right (and will be deemed to have accepted the right) to enforce these Terms of Use against you as a third-party beneficiary thereof; notwithstanding the foregoing, TMC Global’s right to enter into, rescind or terminate any variation, waiver, or settlement under these Terms of Use is not subject to the consent of any third party.<br />
 
By using TMC Global Pay or otherwise by agreeing to these Terms of Use, you agree to receive an eReceipt in lieu of a paper receipt for all purchases made through TMC Global Pay. You must register through a Tmcglobal.com account to receive eReceipts (see below for more information).<br/>
                    There is no charge from us to use TMC Global Pay, but your data service provider’s message and data charges may apply. Except as otherwise provided by law, we may block, restrict, suspend or terminate your use of TMC Global Pay at any time, without notice, and in our sole discretion. 
                    All TMC Global policies applicable to sales occurring at a store location, including those regarding Ad Match, Price Matching, Coupon use, Returns, and Exchanges, apply to purchases made through TMC Global Pay. We reserve the right to limit the availability of TMC Global Pay during specific times, for specific items, or for certain events or promotions. Some products or services may not be eligible for purchase using TMC Global Pay, or may require additional verification prior to completion of purchase through TMC Global Pay. These products and services may include but are not limited to: tobacco, alcohol, firearms, optical or photo products and services, or products requiring a service agreement such as wireless, automotive, or financial products.
                      
D. eReceipts
Certain TMC Global Sites may permit or require the use of electronic receipts (“eReceipt”) for purchases made by you through a mobile device or other electronic device. Your eReceipt is a digital copy of your TMC Global in-store purchase receipt. Any use of the TMC Global eReceipt service is subject to the following additional terms:<br/>

                    To register for eReceipts, you must first have an account with Tmcglobal.com and then validate your mobile number via a text message. tmcglobal.com accounts are subject to these Terms of Use. If you initiate the registration process for eReceipts at the cash register, you will be required to enter a mobile number into the PIN pad and then validate your mobile number via a text message. By registering for TMC Global eReceipts, you consent to receive an automated text message and accept any message and data rates that may apply for receipt of a text message.<br/>
                    There is no charge from us to use TMC Global eReceipts, but your data service provider’s message and data charges may apply. TMC Global and text message carriers are not liable for delayed or undeliverable messages. 
All information provided to TMC Global by users of the TMC Global eReceipts will be subject to our Privacy Policy.
                    We may alter, suspend, or terminate your use of TMC Global eReceipts at any time at our discretion, without notice to you. We are not responsible for any losses associated with your inability to access the I nternet and/or TMC Global eReceipts. Requesting an eReceipt at the register will not automatically submit your eReceipt. Use of the TMC Global eReceipts service is subject to all applicable laws and regulations.<br/> 
                    E. TMC Global Pickup and Delivery (formerly, Online Grocery Services)
                    Use of TMC Global Pickup and delivery is subject to the following additional terms:
                    
                    i. Orders
                    
Once you have placed an order for TMC Global Pickup and delivery, we will send you an order acknowledgment by email setting out what you have ordered. This is not an order confirmation or acceptance from us.<br/>
                    There may be a minimum order value, which may change from time to time. In addition to the price of goods, a delivery charge as shown at checkout, if applicable, will also be payable by you. All prices quoted are exclusive of tax and you will see estimated taxes and fees when you place the order. The final taxes and fees will be calculated on the day your order is picked and delivered, or picked up, as applicable. In the event your order must be fulfilled using products of different weight or volume than what you ordered, you will be charged only for the actual weight or volume delivered.
Due to shipment and delivery times, there are limitations on when changes or cancellations to orders can be made. These limitations will be provided when you place your order. For Pickup and delivery orders that are delivered to you, title to the goods purchased by you and the related risk of loss on these items passes to you upon delivery of the items to the carrier.<br/>
                    We may, in our discretion, provide you with a refund in certain circumstances. If you are not satisfied with your order, please contact the TMC Global Pickup and delivery Contact Center at 1-800- 924-9206.<br />
                    Notwithstanding the foregoing, all refunds will be subject to our discretion. 
                    We aim to deliver your goods within the delivery or pickup window you selected when placing your order, but do not guarantee that goods will be delivered or available for pickup on or by a certain date. TMC Global will not be liable for delivering the goods outside of the requested delivery or pickup slot or failing to deliver or make available for pickup all or any of the goods in your order.<br/>
                    We can only deliver to an a ddress stored in your address book in your account.<br />
                    ii. TMC Global Pickup and delivery Pricing<br />
                    
                    • Pricing for TMC Global Pickup and delivery items will be the same prices as if you shopped in the store that packs and delivers the items. If an item's price changes between the time you place your order and the day your order is packed for delivery, we will charge you the lower price. If you have allowed substitutions for your order, you will be charged the price for items received. Please note that due to differences in distribution, regional competition, and other factors, prices may vary between stores, and so the prices you see online may not match all stores, only the store where your order is packed. TMC Global Pickup and delivery does not match prices from other online or physical stores, or TMC Global stores other than the one where your items are picked and packed.
                    iii. TMC Global Pickup and delivery Promotion Codes<br/>

                    TMC Glob al Pickup and delivery Promotion Codes (“Grocery Promo Codes”) are valid only on orders placed for TMC Global online grocery services, subject to the terms of this Section. Your use of a Grocery Promo Code indicates your agreement to be bound by these Terms of Use and any Grocery Promo Code terms on the promotion offer itself. TMC Global will only honor a Grocery Promo Code if it is used in accordance with all applicable terms.
                    Only promotional codes issued by TMC Globalcan be used for TMC Global Pickup and delivery services. Grocery Promo Codes cannot be used in TMC Global stores. Grocery Promo Codes issued by TMC Global are, and will remain, the property of TMC Global and are not transferable, cannot be resold, and have no cash value unless otherwise stated. Grocery Promo Codes may not be used for alcohol purchases.
Grocery Promo Codes can be added to your TMC Global Pickup and delivery order by entering the code at checkout or by selecting a saved offer in checkout. To apply a Grocery Promo Code to your order, you must select it in the “Review Order” section at checkout. Use of a Grocery Promo Code may be subject to you providing proof of entitlement to use the Grocery Promo Code.
                    All Grocery Promo Codes have an expiration date after which they cannot be used for any order. Grocery Promo Code values may be adjusted if the total discount value is greater than the value of your order.<br />
                    We reserve the right to withdraw or cancel any Grocery Promo Code at any time, either as a whole, or for specific goods or delivery areas. If this happens, then the Grocery Promo Codes may not be used for any orders placed after the date of withdrawal or cancellation. We reserve the right to reject or cancel the use of a Grocery Promo Code where fraud or misuse is suspected. You will have no claim against TMC Global in connection with such rejection or cancellation of a Grocery Promo Code. TMC Global will not be liable to any customer or household for any financial loss arising out of the cancellation or withdrawal of any Grocery Promo Code or any failure or inability of a customer to use a Grocery Promo Code for any reason.
                    Grocery Promo Codes may not be copied, reproduced, published, or distributed directly or indirectly in any form for use by anyone other than the original recipient. By using a Grocery Promo Code, you warrant that you are the duly authorized recipient of it.<br />
                    
                    F. TMC Global Plus Membership<br />
                    TMC Global Plus Membership is subject to terms of use that can be found here: <br />

                    G. TMC Global Digital Photo Center<br/>
                                                 </p>

                    <p className='term-text'>
                        TMC Global claims no ownership rights to the photos, photo files, albums, projects, captions, or prints (collectively defined as “Photos”), that you place in your TMC Global Digital Photo Center Account. However, by uploading Photos into your TMC Global Digital Photo Center Account, you agree to waive all moral rights to those images. In addition, you grant to TMC Global a nonexclusive, worldwide, royalty-free, sublicensable license, so we can download, upload, copy, print, display, reproduce, modify, publish, post, transmit, distribute, and otherwise make available the photos included in your TMC Global Digital Photo Center Account for the following purposes: (1) displaying Photos to the people you select; (2) fulfilling orders; (3) improving the TMC Global Digital Photo Center service and enabling it to work as designed, including by using automated systems and algorithms to analyze and customize your Photos; and (4) developing new technologies and services for TMC Global . We will not use or modify your Photos for any purposes other than the foregoing without obtaining your express permission.
                        You are responsible for monitoring and creating backup copies of the Photos stored in your account. TMC Global Digital Photo Center is not provided to you under any warranty. TMC Global will not be liable for any damage to your photos, albums, rolls, or uploads, including but not limited to loss, deletion or alteration.
                        TMC Global may terminate your service or access to the TMC Global Digital Photo Center and delete any and all information, including but not limited to your Photos, without notice, for any reason including, but not limited to (1) your violation of these Terms of Use or other policies set by TMC Global elsewhere on the TMC Global Sites; (2) online conduct that TMC Global believes is harmful to other customers, the business of TMC Global , or other third-party information providers; and (3) failure to access your account for one (1) year.<br />
                        TMC Global reserves the right to disclose any Photos made available by you or any other customers as necessary to satisfy any law, regulation, or governmental request, or to edit, refuse to submit or to remove any Photos, in whole or in part, that in TMC Global’s judgment are unsuitable or in violation of these Terms of Use or other policy set by TMC Global elsewhere on the TMC Global Sites. TMC Global may delete, move, and edit Photos for any reason, at any time, without notice.<br />
                        By making available Photos, you warrant that you are the sole author and owner of the Photos, or that you have obtained all required releases or permissions to permit copying, printing, licensing of the Photos, and your use of the TMC Global Digital Photo Center, as set forth in these Terms of Use.<br />
                        TMC Global reserves the right to require<br /> that you obtain a signed copyright release form from the photographer or studio for photographs that are signed, stamped, or otherwise identified by any photographer or studio as copyrighted material, or any photograph that appears to have been taken by a professional photographer or studio, even if it is not marked with any sort of copyright. In such cases, negatives or digital images of a copyrighted image will be returned to you unprinted and you will be provided instructions on how to present TMC Global with a signed copyright release. Copyright owner release forms and copyright permission release forms are available in-store at the TMC Global Digital Photo Center.<br />
                        TMC Global will not assist in the copying of any state or federal document, including but not limited to driver's licenses, passports, and social security cards.<br />
                        As a convenience to TMC Global customers, TMC Global may make third-party software available through the TMC Global Digital Photo Center either through physical distribution or by download. To use such software, you will agree to the terms and conditions imposed by the third party provider. Unless otherwise stated in any specific agreement, the agreement to use such software will be solely between you and the third party provider.<br />
                        TMC Global uses commercially reasonable efforts to maintain the availability of the TMC Global Digital Photo Center 24 hours a day, 7 days a week, and provide photo processing within the time frame communicated to you. However, TMC Global will not be liable to you for any unexpected outage or disruption of service. One-hour photo services are subject to limitations on store equipment and processing capacity, and actual pick-up times may vary.<br />
                        Making available any Photos to TMC Global for processing, printing, storage, transmission or other handling constitutes an agreement by you that any damage to your Photos or computer system, or any loss of data, by TMC Global , its subsidiaries, employees, or agents, even if caused by negligence or other fault, will only entitle you to replacement with a like amount of storage and processing. Except for replacement, to the fullest extent provided by applicable law, the handling of any Photos is not under warranty or liability, and recovery for any incidental or consequential damages is excluded.<br />
                        You understand and agree that any Content, including but not limited to Photos and software, downloaded or otherwise obtained through the use of the TMC Global Digital Photo Center is done at your own discretion and risk and that you will be solely responsible for any damages to your computer system or loss of data that may result in the download or upload of such material. Your use of the TMC Global Digital Photo Center may expose you to Photos you may feel objectionable. You take sole responsibility for such exposure.<br />
                        H. Reserved.<br />
                        I. TMC Global Registry for Good
                    </p>
                    <p className='term-text'>
                        i. Eligibility

                        Participation in Registry for Good Site is limited to Tmcglobal.com accounts that have been associated with an eligible recognized 501(c)(3) organization (“Charity”) as verified by TMC Global or its third party service provider. Each Tmcglobal.com account may create only one Registry for Good.
                        Charities may be required to verify their compliance with these Terms, including verification that the Charity meets, or continues to meet the definition of a charity. TMC Global may monitor the Charity’s website or other information to verify its compliance with these Terms.
                        ii. Solicitation

                        Charities may elect to make their Registry for Good searchable on the Registry for Good Site or may elect to make the registry private and available only to those who have a link.
                        Charities are solely responsible for compliance with all solicitation regulations under each jurisdiction where they promote their Registry for Good, or the Registry for Good Site or any portion thereof.
                        Charities acknowledge and agree that they are not entitled to receive, and TMC Global will not provide, any identifiable customer information in respect of purchases made from any Registry for Good. TMC Global will not promote any Charity or its Registry for Good.
                        iii. List Address

                        tmcglobal.com customers may purchase items selected by a Charity for its registry and choose to direct TMC Global to deliver them to the address designated by the Charity (“List Address”) or customers may choose to deliver the items to the Charity directly.
                        List Addresses provided by the Charity must be owned or leased by the Charity. Charities must promptly update their List Address (and any other information requested by TMC Global ) if the Charity address changes or it ceases holding a valid ownership or leasehold interest in the List Address. An agreement with a mail delivery agent or delivery service is not considered a leasehold for purposes of these Terms. By participating in the Registry for Good program, Charities consent and allow TMC Global or any of its affiliates to share the List Address with any seller that offers items on your Registry for Good that a customer elects to purchase and send to the Charity List Address.
                        iv. Charity Promotion

                        Charities may only promote or link to their Registry for Good on their own website, user-generated content published through a social media account, or page belonging to the Charity, offline mailings, or email correspondence, and may only use such of TMC Global’s trademarks or logos, links to the Registry for Good Site, or other TMC Global Content TMC Global may make available to the Charity, in all cases in accordance with the following restrictions:
                        Charities may not promote or link to the Registry for Good, or the Registry for Good Site, in a way that is misleading, illegal, or confusing to viewers or that does not accurately represent the Registry for Good program.
                        Charities may not state, or imply that TMC Global funds, endorses, supports or is otherwise engaged in business with a Charity.
                        Charities may not request, collect, obtain, store, cache, or otherwise use any account information of, or used by, other TMC Global customers.
                        Charities may not modify, redirect, suppress, or substitute the operation of any button, link, or other feature of the TMC Global Content or the Registry for Good Site.
                        Charities may not frame your Registry for Good or the Registry for Good Site, or any part of it, on your own website, social media account, mailings or correspondence. Displaying a link in accordance with these Terms will not be considered framing.
                        TMC Global reserves the right to terminate any Charity participation in the Registry for Good, or suspend access to the Registry for Good site for violation of these Terms, in addition to any other remedies available to TMC Global under these Terms or applicable law.
                        17. Disclaimer of Warranties
                        THE TMC Global SITES, AND ALL CONTENT, MATERIALS, PRODUCTS, SERVICES, FUNCTIONALITY, AND OTHER ITEMS INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE TMC Global SITES, AND/OR TMC Global STORE LOCATIONS, ARE PROVIDED BY TMC Global ON AN “AS IS” AND “AS AVAILABLE” BASIS. NO TMC Global ENTITY MAKES ANY REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE TMC Global SITES OR THE CONTENT, MATERIALS, PRODUCTS, SERVICES, FUNCTIONALITY, OR OTHER ITEMS INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, THE TMC Global ENTITIES DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. WITHOUT LIMITING THE FOREGOING, THE TMC Global ENTITIES DISCLAIM ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, FOR ANY MERCHANDISE OFFERED. YOU ACKNOWLEDGE THAT, TO THE FULLEST EXTENT PROVIDED BY APPLICABLE LAW, YOUR USE OF THE TMC Global SITES IS AT YOUR SOLE RISK. THIS SECTION 17 DOES NOT LIMIT THE TERMS OF ANY PRODUCT WARRANTY OFFERED BY THE MANUFACTURER OF AN ITEM THAT IS SOLD BY TMC Global TO YOU. THIS DISCLAIMER CONSTITUTES AN ESSENTIAL PART OF THESE TERMS OF USE. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU ASSUME FULL RESPONSIBILITY FOR YOUR USE OF THE TMC Global SITES AND AGREE THAT ANY INFORMATION YOU SEND OR RECEIVE DURING YOUR USE OF THE TMC Global SITES MAY NOT BE SECURE AND MAY BE INTERCEPTED OR OTHERWISE ACCESSED BY UNAUTHORIZED PARTIES. YOU AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NO TMC Global ENTITY IS RESPONSIBLE FOR ANY LOSS OR DAMAGE TO YOUR PROPERTY OR DATA THAT RESULTS FROM ANY MATERIALS YOU ACCESS OR DOWNLOAD FROM THE TMC Global SITES. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE FOREGOING LIMITATIONS MAY NOT APPLY TO YOU.

                        18. Limitation of Liability
                        YOU ACKNOWLEDGE AND AGREE THAT, TO THE FULLEST EXTENT PROVIDED BY APPLICABLE LAW, TMC Global ENTITIES WILL NOT BE LIABLE TO YOU OR TO ANY OTHER PERSON UNDER ANY CIRCUMSTANCES OR UNDER ANY LEGAL OR EQUITABLE THEORY, WHETHER IN TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE, FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL LOSSES OR DAMAGES OF ANY NATURE EVEN IF AN AUTHORIZED REPRESENTATIVE OF A TMC Global ENTITY HAS BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. TO THE FULLEST EXTENT PROVIDED BY APPLICABLE LAW, THIS DISCLAIMER APPLIES TO, BUT IS NOT LIMITED TO, ANY DAMAGES OR INJURY ARISING FROM ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECTS, DELAY IN OPERATION OR TRANSMISSION, LOST PROFITS, LOSS OF GOODWILL, LOSS OF DATA, WORK STOPPAGE, ACCURACY OF RESULTS, COMPUTER FAILURE OR MALFUNCTION, COMPUTER VIRUSES, FILE CORRUPTION, COMMUNICATION FAILURE, NETWORK OR SYSTEM OUTAGE, THEFT, DESTRUCTION, UNAUTHORIZED ACCESS TO, ALTERATION OF, LOSS OF USE OF ANY RECORD OR DATA, AND ANY OTHER TANGIBLE OR INTANGIBLE LOSS. SUBJECT TO THE FOREGOING, TO THE FULLEST EXTENT PROVIDED BY APPLICABLE LAW, NO TMC Global ENTITY WILL BE LIABLE FOR ANY DAMAGES IN EXCESS OF THE FEES PAID BY YOU IN CONNECTION WITH YOUR USE OF THE TMC Global SITES DURING THE SIX (6) MONTH PERIOD PRECEDING THE DATE ON WHICH THE CLAIM AROSE.

                        YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT, TO THE FULLEST EXTENT PROVIDED BY APPLICABLE LAW, NO TMC Global ENTITY WILL BE LIABLE FOR ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY SELLER (INCLUDING ANY MARKETPLACE RETAILER), SHOPPER, OR OTHER USER OF THE TMC Global SITES.

                        19. Indemnification
                        You agree to defend (at TMC Global’s option), indemnify, and hold the TMC Global Entities harmless from and against any and all liabilities, claims, damages, costs, and expenses, including attorneys’ fees and costs, arising from or related to your misuse of the TMC Global Sites or any breach by you of these Terms of Use. TMC Global reserves the right, at our expense, to assume exclusive defense and control of any matter otherwise subject to indemnification by you and, in any case, you agree to cooperate with TMC Global if and as requested by TMC Global in the defense and settlement of such matter.

                        20. Disputes, Arbitration, and Applicable Law
                        PLEASE READ THIS SECTION CAREFULLY. IT MAY SIGNIFICANTLY AFFECT YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT.

                        Arbitration Agreement.
                        EXCEPT FOR DISPUTES THAT QUALIFY FOR SMALL CLAIMS COURT, YOU AGREE THAT ALL DISPUTES ARISING OUT OF OR RELATED TO THESE TERMS OF USE OR ANY ASPECT OF THE RELATIONSHIP BETWEEN YOU AND TMC Global , INCLUDING ANY PRODUCTS OR SERVICES OFFERED OR SOLD BY TMC Global OR THE TMC Global ENTITIES, WHETHER BASED IN CONTRACT, TORT, STATUTE, FRAUD, MISREPRESENTATION, OR ANY OTHER LEGAL THEORY, WILL BE RESOLVED THROUGH FINAL AND BINDING ARBITRATION BEFORE A SINGLE NEUTRAL ARBITRATOR INSTEAD OF IN A COURT BY A JUDGE OR JURY. EXCEPT AS OTHERWISE PROVIDED IN THESE TERMS OF USE, YOU AND TMC Global AGREE THAT EACH IS WAIVING THE RIGHT TO SUE IN COURT AND TO HAVE A TRIAL BY A JURY. This paragraph may be referred to as the Arbitration Agreement in these Terms of Use.

                        Class Action and Mass Action Waiver.
                        YOU AND TMC Global AGREE THAT ANY ARBITRATION REQUIRED BY THE ARBITRATION AGREEMENT WILL TAKE PLACE ON AN INDIVIDUAL BASIS. You and TMC Global each agree to waive the right to have any dispute or claim subject to the Arbitration Agreement brought, heard, administered, resolved, or arbitrated as a class arbitration, class action, collective action, or Mass Action to the maximum extent permitted by law. “Mass Action” means a situation in which a party is represented by a law firm or other representative, or a collection of law firms or other representatives, that has initiated more than one hundred (100) arbitration Demands with common questions of law or fact against TMC Global within 180 days of initiating your arbitration Demand. This paragraph may be referred to as the “Class Action and Mass Action Waiver” in these Terms of Use. Nothing in these Terms of Use precludes you from bringing issues to the attention of federal, state, or local government agencies and, if the applicable law allows, such agencies may seek relief against TMC Global for you.

                        Initiating a Demand for Arbitration.
                        Any arbitration required by the Arbitration Agreement shall be initiated by You or TMC Global by sending the other a written demand for arbitration (“Demand”) only via first-class mail, FedEx, or UPS within the statute of limitations period. Your Demand shall be delivered to: TMC Global Inc. Legal Department, 702 SW 8th Street, Mailstop 0215, Bentonville, AR 72716. The Demand must include (i) the name, telephone number, mailing address, and email address of the person or entity seeking arbitration; (ii) a statement of the legal claims asserted and the factual basis for those claims; (iii) a description of the remedy sought and an accurate, good-faith calculation of the amount in controversy; (iv) the original personal signature of the party seeking arbitration; and (v) the original personal signature of any legal counsel or other representative purporting to represent the party seeking arbitration. For purposes of this paragraph, “original personal signature” does not include any digital, scanned, electronic, copied, or facsimile signature. An original personal signature on the Demand certifies the following: (i) the Demand is not being presented for any improper purpose, such as to harass, cause unnecessary delay, or needlessly increase the cost of litigation; (ii) the claims and other legal contentions are warranted by existing law or by a non-frivolous argument for extending, modifying, or reversing existing law or for establishing new law; and (iii) the factual contentions have evidentiary support or, if specifically so identified, will likely have evidentiary support after a reasonable opportunity for further investigation or discovery. The original personal signature by the party seeking arbitration shall verify under penalty of perjury that the factual statements contained in the Demand are true and correct. Compliance with this paragraph tolls any applicable statute of limitations as to any dispute or claim subject to the Arbitration Agreement that is stated in the Demand.

                        Filing a Demand for Arbitration.
                        A party seeking arbitration of any dispute or claim subject to the Arbitration Agreement shall submit a copy of the Demand to the American Arbitration Association (“AAA”) sixty (60) or more days after the Demand is initiated pursuant to Section 20.3 of these Terms of Use. The arbitration will be administered by the AAA pursuant to the current AAA Consumer Arbitration Rules, except to the extent modified by these Terms of Use. The AAA rules and instructions are available on the AAA website at www.adr.org/consumer.

                        Conduct of Arbitration.
                        In any arbitration of a dispute or claim that is subject to the Arbitration Agreement:

                        You or TMC Global may file such dispositive motions as would be permitted by the Federal Rules of Civil Procedure without obtaining permission from the arbitrator. Upon the filing of any dispositive motion<br />, the arbitrator may stay all further action and deadlines in the arbitration until deciding such motion.<br />
                        The parties shall have the right to conduct such discovery from the opposing party or any third party that is proportional to the needs of the claim or dispute, considering the importance of the issues at stake, the amount in controversy, the importance of the discovery in resolving the issues, and whether the burden or expense of the proposed discovery outweighs its likely benefit. Proportionality shall be decided by the arbitrator when requested by either party.<br />
                        The arbitrator shall conduct any calls, conferences, or hearings by teleconference or videoconference, unless the arbitrator determines that an in-person hearing is appropriate. Any in-person hearing will be held at a location that is reasonably convenient. You and an employee of TMC Global shall attend all arbitrator calls, conferences, and hearings.<br />
                        A party may make a written offer of judgment at least seven (7) days before the date set for the arbitration hearing.
                        If the arbitrator finds that a party’s claim, counterclaim, or appeal was frivolous, asserted in bad faith, or pursued for purposes of harassment, the arbitrator shall award the opposing party its attorneys’ <br />fees, costs, and expenses and all amounts charged by AAA for the arbitration.<br />
                        The arbitrator will follow these Terms of Use and the law. The arbitrator shall not have the authority to commit errors of law or legal reasoning. The arbitrator may award relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that individual party’s claim. The arbitrator may not award relief for or against anyone who is not a party, though the individual relief awarded by the arbitrator may incidentally affect non-parties.
                        You or TMC Global may appeal an arbitration award that manifestly disregards the law by filing a notice of appeal with the AAA within 30 days after an award is rendered and delivered to the parties. The appeal shall be heard by a single arbitrator unless the parties agree to a multi-arbitrator appellate panel. The arbitrator(s) assigned to the appeal shall be selected by agreement of the parties from among those on the AAA Appellate Panel. If the parties are unable to agree, AAA shall appoint the arbitrator(s) from among those on the AAA Appellate Panel. An arbitrator who previously presided over any aspect of a case shall be ineligible from serving as an appellate arbitrator in that same case. The appeal, including briefing, shall be conducted pursuant to the parties’ agreement or the appellate arbitrator(s)’ orders if the parties are unable to agree.
                        Process for Arbitration Bellwether Demands.
                        If twenty-five (25) or more Demands for arbitration of a dispute or claim subject to the Arbitration Agreement are initiated (i) that involve common questions of law or fact and (ii) where the initiating parties are represented by the same law firm, the same group of coordinated law firms,<br /> or the same representative, then such Demands shall be coordinated pursuant to this paragraph. The group of claimants and group of respondents shall each select five (5) Demands, for a total of ten (10), to be filed with AAA (collectively the “Bellwether Demands”). Each of the Bellwether Demands shall be assigned by AAA to a different arbitrator chosen from its national roster. After ninety (90) days from the date all Bellwether Demands have been arbitrated and any appeals exhausted, any remaining Demands subject to this paragraph may be filed with AAA. The AAA Supplementary Rules for Multiple Case Filings shall apply to the extent they are not inconsistent with this paragraph. Notwithstanding any other provision in the Terms of Use, You and TMC Global agree that a court of competent jurisdiction shall have authority to enforce the terms of this paragraph with injunctive or other relief.

                        Severability.
                        If (i) any dispute or claim subject to the Arbitration Agreement is filed as a class arbitration, class action, collective action, representative action, or Mass Action and (ii) if the Class Action and Mass Action Waiver is held invalid or unenforceable as to such dispute or claim, then the Arbitration Agreement does not apply to that dispute or claim and such dispute or claim must be brought in a court of competent jurisdiction. If any provision of Section 20 other than the Class Action and Mass Action Waiver is held invalid or unenforceable as to a particular dispute or claim, then such provision shall be severed from the Terms of Use, and the remainder of the Terms of Use shall be enforceable to the maximum extent permitted by law.

                        Applicable Law.
                        The Federal Arbitration Act (“FAA”) governs the interpretation and enforcement of Section 20 of these Terms of Use. If the FAA is found not to apply to any portion of Section 20 of these Terms of Use, then the applicable laws of the State of Arkansas shall apply without regard to choice-of-law principles<br />
                    </p>

                    <p className='term-text'>


                        21. Termination<br />
                        These Terms of Use are effective unless and until terminated by either you or TMC Global. You may terminate these Terms of Use at any time, provided that you discontinue any further use of the TMC Global Sites.<br /> We also may terminate these Terms of Use at any time and may do so immediately without notice, and deny you access to the TMC Global Sites, if in our sole discretion you fail to comply with any term or provision of these Terms of Use. Upon any termination of these Terms of Use by either you or TMC Global , you must promptly destroy all Materials and other Content downloaded or otherwise obtained from the TMC Global Sites, as well as all copies of such Content, whether made under these Terms of Use or otherwise. The following sections will survive any termination of these Terms of Use: “Your Use of the TMC Global Sites,” “Content and Ideas,” “Monitoring by TMC Global ,” “Materials Available on the TMC Global Sites,” “Merchandise,” “Third Party Sites,” “Placing an Order with TMC Global ,” “Shipping and Delivery,” “Export Policy,” “Intellectual Property” (excluding the rights granted to you in that Section), “Privacy,” “Third-Party Software & Licensing Notices,” “Indemnification,” “Termination,” “Disclaimer of Warranties,” “Limitation of Liability,” “Disputes & Arbitration,” and “General”.
                    </p>

                    <p className='term-text'>
                        22. General<br></br>
                        These Terms of Use represent the complete agreement and understanding between you and TMC Global and supersede all prior agreements and representations between<br /> the parties with respect to the subject matter of these Terms of Use. These Terms of Use do not, and shall not be construed to, create any partnership, joint venture, employer-employee, agency, or franchisor-franchisee relationship between you and TMC Global. Headings used in these Terms of Use are for reference purposes only and in no way define or limit the scope of the section. Except as provided in Section 20 above, if any provision of these Terms of Use is held to be unenforceable for any reason, such provision will be reformed only to the extent necessary to make it enforceable and the other terms of these Terms of Use will remain in full force and effect. Except as provided in Section 20 above, these Terms of Use shall be interpreted and governed by the applicable laws of the State of Arkansas without regard to choice-of-law principles. The failure of TMC Global to act with respect to a breach of these Terms of Use by you or others does not constitute a waiver and will not limit TMC Global's rights with respect to such breach or any subsequent breaches. You may not assign, transfer, or sublicense any or all of your rights or obligations under these Terms of Use without our express prior written consent. We may assign, transfer, or sublicense any or all of our rights or obligations under these Terms of Use without restriction. Any use of the term “including” or variations thereof in these Terms of Use shall be construed as if followed by the phrase “without limitation.” Notices to you (including notices of changes to this these Terms of Use) may be made via posting to the TMC Global Sites or by e-mail (including in each case via links), or by regular mail. Without limitation, a printed version of these Terms of Use and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms of Use to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.
                    </p>
                    <p className='term-text'>
                        23. Filtering<br />
                        This is to notify you that parental control protections (such as computer hardware, software, or filtering services) are commercially available that may assist you in limiting access to material that is harmful to minors.<br /> Information identifying current providers of such protections is available from https://en.wikipedia.org/wiki/Comparison_of_content-control_software_and_providers.<br /> Please note that we do not endorse any of the products or services listed on such site.
                    </p>
                    
                

























  </Container>

  </>
            )
}
        
export default page