import { Poppins } from "next/font/google";
// import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/components/shared/header/Header";
import TmaFooter from "@/components/shared/footer/TmaFooter";


export const rock = Poppins({
  subsets: ["latin"],
  weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "TMA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rock.className}>
        <Header />
        {children}
        <TmaFooter />
      </body>
    </html>
  );
}
